name: Build and Upload Executables

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.5"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed Hash_Cracker_GUI.py

      - name: Rename and move executable
        shell: bash
        run: |
          mkdir dist_release
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            mv dist/Hash_Cracker_GUI.exe dist_release/Hash_Cracker_GUI_Windows.exe
          else
            mv dist/Hash_Cracker_GUI dist_release/Hash_Cracker_GUI_Linux
          fi

      - name: Upload executable to release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist_release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
